//! Optional WirePlumber quirk for the Arctis Nova Pro Wireless: the device's
//! USB playback SYNC endpoint has no explicit feedback, which causes audible
//! crackle on some systems. Forcing `api.alsa.headroom` compensates (the same
//! fix loteran/Arctis-Sound-Manager ships). ~4096 frames ≈ +85 ms latency, so
//! it's opt-in rather than always on.
//!
//! We render a WirePlumber 0.5 conf fragment; presence of the file *is* the
//! on/off state, so no extra preference needs persisting.

use std::fs;
use std::path::PathBuf;

use crate::error::SinkError;

const HEADROOM_FRAMES: u32 = 4096;

pub fn conf_path() -> Result<PathBuf, SinkError> {
    let dir = dirs::config_dir()
        .ok_or_else(|| SinkError::Config("cannot resolve the user config directory".into()))?;
    Ok(dir
        .join("wireplumber")
        .join("wireplumber.conf.d")
        .join("51-arctis-nova-pro-headroom.conf"))
}

/// True when the headroom fix is currently installed.
pub fn is_enabled() -> bool {
    conf_path().map(|p| p.exists()).unwrap_or(false)
}

fn fragment() -> String {
    format!(
        "# Generated by Sink. Anti-crackle headroom for the Arctis Nova Pro\n\
         # Wireless USB playback node. Toggle from the Headset panel.\n\
         monitor.alsa.rules = [\n\
         \x20 {{\n\
         \x20   matches = [\n\
         \x20     {{ node.name = \"~alsa_output.*[Aa]rctis.*[Nn]ova.*[Pp]ro.*\" }}\n\
         \x20   ]\n\
         \x20   actions = {{\n\
         \x20     update-props = {{\n\
         \x20       api.alsa.headroom = {HEADROOM_FRAMES}\n\
         \x20     }}\n\
         \x20   }}\n\
         \x20 }}\n\
         ]\n"
    )
}

/// Install or remove the fragment. We deliberately do NOT restart WirePlumber:
/// a restart tears down Sink's own virtual sinks and mic chain (leaving apps
/// like Discord pointing at a dead `sink_mic`), so the quirk applies on the
/// next login / WirePlumber restart instead. The UI tells the user this.
pub fn set_enabled(enabled: bool) -> Result<(), SinkError> {
    let path = conf_path()?;
    if enabled {
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)?;
        }
        super::write_atomic(&path, fragment())?;
    } else if path.exists() {
        fs::remove_file(&path)?;
    }
    Ok(())
}
